### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by Heath123** [Tobi406/Aliasr#1]
There's no license for the code that I can see.
https://choosealicense.com/
(by the way I'm trying to use this to work out how to add commands in a Velocity plugin)

**Comment by Tobi406** [comment]
Thanks for reporting!

**Comment by Tobi406** [comment]
I add the command in [AliasrCommand.java](https://github.com/Tobi406/Aliasr/blob/master/src/main/java/com/github/tobi406/aliasr/AliasrCommand.java) and register it in [AliasrPlugin.java#L89](https://github.com/Tobi406/Aliasr/blob/master/src/main/java/com/github/tobi406/aliasr/AliasrPlugin.java#L89) by the way.
